name = "PairCorrelationFunction"
uuid = "1da3c5ec-5de6-497d-83f1-8bbf7fdc92ec"
authors = ["Daniel Bergman <danielrbergman@gmail.com> and contributors"]
version = "0.0.13"

[deps]
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
NaNStatistics = "0.6"
PlotUtils = "1.4.3"
RecipesBase = "1.3.4"
julia = "1.6.7"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
